version: '3.8'

services:
  web:
    build: .
    container_name: bit_academy_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: bit_academy_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
